### ISSUE TITLE
userbase.deleteItem is not a function

### ISSUE THREAD

**Issue by gduverger** [encrypted-dev/userbase-homepage#5]
When calling `deleteItem` in `userbase-0.0.6` I get the following error message:
```
Uncaught TypeError: userbase.deleteItem is not a function
```

It looks like that function might have been replaced by `delete`. If so, could we update the documentation? I'm happy to open a PR for it, I just wanted to make sure I didn't miss something obvious first.

Keep up the good work!

**Comment by dvassallo** [comment]
You're right. We just renamed insert/update/delete to insertItem, updateItem, and deleteItem. We haven't published the latest SDK yet because it has some other breaking changes, so the docs are slightly out of sync (ahead) of the SDK version you're using. In the meantime, you can still find the old docs here that are compatible with your SDK version: https://5dc0a33b2551f40008af055c--userbase.netlify.com/docs/

**Comment by gduverger** [comment]
Thanks for the clarification, @dvassallo. Am I correct to also assume that `userbase.signInWithSession` has been replaced with the session being directly returned in `userbase.init`?

**Comment by j-berman** [comment]
@gduverger You are correct!
